// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ672rm5kMXsy1RJrj2ebGrOj4Ml6K9Ro',
    appId: '1:209611532391:web:b21601428bfa3e6facccc2',
    messagingSenderId: '209611532391',
    projectId: 'fir-fotos-16ef6',
    authDomain: 'fir-fotos-16ef6.firebaseapp.com',
    storageBucket: 'fir-fotos-16ef6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARdDJUQPQeV9xPtILnlCc3CSYsMwG6bbs',
    appId: '1:209611532391:android:4f0a4d6a0235edebacccc2',
    messagingSenderId: '209611532391',
    projectId: 'fir-fotos-16ef6',
    storageBucket: 'fir-fotos-16ef6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL1SILkRwqhrnfS0YuPtj_QL1T0TSyZmY',
    appId: '1:209611532391:ios:001ef414c8e6ce1cacccc2',
    messagingSenderId: '209611532391',
    projectId: 'fir-fotos-16ef6',
    storageBucket: 'fir-fotos-16ef6.appspot.com',
    iosBundleId: 'com.example.firefotos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL1SILkRwqhrnfS0YuPtj_QL1T0TSyZmY',
    appId: '1:209611532391:ios:da00b2af8014d554acccc2',
    messagingSenderId: '209611532391',
    projectId: 'fir-fotos-16ef6',
    storageBucket: 'fir-fotos-16ef6.appspot.com',
    iosBundleId: 'com.example.firefotos.RunnerTests',
  );
}
